# Generated by Django 6.1.1 on 2026-10-03 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_property_type_rentalrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '5 Stars - Excellent'), (4, '4 Stars - Very Good'), (3, '3 Stars - Good'), (2, '2 Stars - Fair'), (1, '1 Star - Poor')], default=5, help_text='Rating from 1 to 5')),
                ('comment', models.TextField(help_text='Review comment from tenant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review & Rating',
                'verbose_name_plural': 'Reviews & Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('property', 'tenant')},
            },
        ),
    ]
