# Generated by Django 6.1.1 on 2026-09-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], max_length=10)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('contact_info', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_image/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resolved', 'Resolved')], default='Active', max_length=20)),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
