# Generated by Django 6.1.1 on 2026-09-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
